name: 'Improve Sanity Check'
description: 'Check the sanity of improve using improve-selenium project'
inputs:
  api-base-url:
    description: 'The API base url to run the tests against. Ignored if running against local setup.'
    required: true
    
  admin-base-url:
    description: 'The admin portal base url to run the tests against. Ignored if running against local setup.'
    required: true
    
  app-base-url:
    description: 'The application portal base url to run the tests against. Ignored if running against local setup.'
    required: true
    
  sanity-secrets:
    description: 'All of the secrets needed by selenium project for running test.'
    required: true
  selenium-image:
    description: 'The url for selenium image'
    required: true
    

outputs:
  sanity-failed:
    value: ${{ steps.sanity-check.outputs.sanity-failed }}
runs:
  using: "composite"
  steps:

    - name: Run sanity-check extension against the required environment
      id: sanity-check
      shell: bash
      run: |
        mkdir /tmp/reports
        chmod 777 /tmp/reports
        export FAILED=0
        export $(echo "${{ inputs.sanity-secrets }}" | xargs)
        echo testing username: $SELENIUM_USERNAME
        docker container run -v "/tmp/reports":"/home/testing/reports" --rm \
          -e API_BASE_URL="${{ inputs.api-base-url }}" \
          -e APP_BASE_URL="${{ inputs.app-base-url }}" \
          -e ADMIN_BASE_URL="${{ inputs.admin-base-url }}" \
          -e SELENIUM_USERNAME=${SELENIUM_USERNAME} \
          -e SELENIUM_USER_PASSWORD=${SELENIUM_USER_PASSWORD} \
          -e PROTON_MAIL=${PROTON_MAIL} \
          -e PROTON_MAIL_PASSWORD=${PROTON_MAIL_PASSWORD} \
          -e API_USER=${API_USER} \
          -e API_USER_PASSWORD=${API_USER_PASSWORD} \
          -e API_ADMIN_USER=${API_ADMIN_USER} \
          -e API_ADMIN_PASSWORD=${API_ADMIN_PASSWORD} \
          -e G_ADMIN_PASSWORD=${G_ADMIN_PASSWORD} \
          -e G_USER_PASSWORD=${G_USER_PASSWORD} \
          ${{ inputs.selenium-image }} || FAILED=1
        echo "::set-output name=sanity-failed::$FAILED"
